[package]
name = "contracts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers.workspace = true
convert_case = "0.6.0"
walkdir = "2.5.0"

[dev-dependencies]
criterion.workspace = true