[package]
name = "inspectah_giving"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
pools-graph.workspace = true
utils.workspace = true
anyhow.workspace = true
once_cell.workspace = true
revm.workspace = true
ethers.workspace = true